language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

env:
  - REQUESTS=2.21
  - REQUESTS=2.22
  - REQUESTS=dev

cache: pip

matrix:
  fast_finish: true

# No support for Python 3.2- in virtualenv 14+
install:
  - travis_retry pip install "virtualenv<14.0.0" "tox>=1.9" "pip>9.0.1"

script:
  - tox -e py$(echo $(echo $TRAVIS_PYTHON_VERSION | sed -e 's/pypy/py/')-requests$REQUESTS | tr -d .)-travis -- --cov=payplug
