trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

stages:
  - stage: tests
    displayName: Run tests
    jobs:
      - template: .ci/templates/docker-jobs.yml
        parameters:
          jobs:
            - job: test
              displayName: Run test
              strategy:
                matrix:
                  Python27:
                    container: 'python:2.7'
                  Python35:
                    container: 'python:3.5'
                  Python36:
                    container: 'python:3.6'
                  Python37:
                    container: 'python:3.7'
              steps:
                - script: |
                    easy_install pip --upgrade
                    pip install --upgrade setuptools pbr
                    python setup.py test

  - stage: checks
    displayName: Static checks
    jobs:
      - template: .ci/templates/docker-jobs.yml
        parameters:
          jobs:
            - job: flake8
              displayName: Run Flake8
              steps:
                - script: |
                    python --version
                    pip install flake8 --user
                    pip freeze
                    python -m flake8
