trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

  pool:
    vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'

  stages:
#  - stage: checks
#    displayName: Static checks
#    jobs:
#      - template: .ci/templates/docker-jobs.yml
#        parameters:
#          jobs:
#            - job: flake8
#              displayName: Run Flake8
#              steps:
#                - script: |
#                    python --version
#                    pip install flake8 --user
#                    flake8 application --exclude="application/config*" lib setup.py tasks tests tools

  - stage: tests
    displayName: Run tests
    jobs:
      - template: .ci/templates/docker-jobs.yml
        parameters:
          jobs:
            - job: test
              displayName: Run test
              steps:
                - script: |
                    easy_install pip --upgrade
                    pip install --upgrade setuptools pbr
                    python setup.py test
